import Document, {Html, Head, Main, NextScript, DocumentContext, DocumentInitialProps} from "next/document";

export default class MyDocument extends Document {
    static async getInitialProps(ctx: DocumentContext):Promise<DocumentInitialProps> {
        const initialProps = await Document.getInitialProps(ctx)
        return { ...initialProps}
    }

    render() {
        return (
            <Html lang="ru">
                <Head>
                    <title>Мир врача</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="preconnect" href="https://fonts.googleapis.com"/>
                    <link rel="preconnect" href="https://fonts.gstatic.com" />
                    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,700;1,400&display=swap"
                          rel="stylesheet" />
                </Head>
                <body>
                <Main />
                <NextScript />
                </body>
            </Html>
        )
    }
}